[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "g4x_helpers"
version = "0.0.3"

description = "Python helpers for G4X."
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name = "Kenneth Gouin III", email = "kennethg@singulargenomics.com"},
  { name = "Florian Raths", email = "flo.rathsg@singulargenomics.com"}
]
requires-python = ">=3.10,<3.11"
dynamic = ["dependencies"]

classifiers = [
  "Private :: Do Not Upload",
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
]

urls = { Homepage = "https://github.com/Singular-Genomics/G4X-helpers" }

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.6",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.12",
]


[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
