name: Setup project environment
description: Checkout repo + submodule, set up project with uv

inputs:
  docs-submodule-token:
    description: Token used to fetch docs assets submodule
    required: false
    default: ''

runs:
  using: composite

  steps:      
    - name: Fetch submodule
      if: ${{ inputs.docs-submodule-token != '' }} # Only run if a token was passed
      uses: actions/checkout@v5
      with:
        fetch-depth: 1
        submodules: recursive
        token: ${{ inputs.docs-submodule-token }}

    - name: Pull latest changes for submodules
      if: ${{ inputs.docs-submodule-token != '' }}
      shell: bash
      run: |
        git submodule update --init --recursive docs/_core
        cd docs/_core
        git fetch origin
        git checkout main
        git pull origin main

    - name: Checkout repo
      uses: actions/checkout@v5
      with:
        fetch-depth: 1
        clean: false # do not clean the working directory as this would remove the submodule changes

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version-file: pyproject.toml

    - name: uv sync
      shell: bash
      run: |
        uv sync --no-progress
    
    - name: uv build
      shell: bash
      run: |
        uv build
