# .github/workflows/build-image.yml
name: Build Docker image on new tag

# Trigger on sem-version tag
on:
  push:
    tags:
      - 'v*.*.*'          # e.g. v1.2.3
  workflow_dispatch:

permissions:
  contents: read          # read source
  packages: write         # push to GHCR

jobs:
  build:
    if: github.repository == 'singular-genomics/g4x-helpers' # Avoid running in forks that copy this workflow
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1  # faster, more efficient builds

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # === Multi-arch / caching prerequisites =============================
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    # ====================================================================
    
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    
    - name: Build & push image (latest + version tag)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/singular-genomics/g4x-helpers:latest
          ghcr.io/singular-genomics/g4x-helpers:${{ github.ref_name }}
       
        platforms: linux/amd64,linux/arm64
        # Optional registry-cache configuration ----------------------
        cache-from: type=registry,ref=ghcr.io/singular-genomics/g4x-helpers:cache
        cache-to:   type=registry,ref=ghcr.io/singular-genomics/g4x-helpers:cache,mode=max