# .github/workflows/publish.yml
name: Publish

on:
  push:
    tags:
      - v*  # e.g. v0.1.0
  workflow_dispatch:

jobs:
  G4X-helpers_PyPI:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Project Environment
        uses: ./.github/actions/setup-project

      - name: Validate PyPI publishing
        if: github.event_name == 'workflow_dispatch'
        run: uv publish --dry-run --trusted-publishing always

      - name: Publish
        if: github.event_name == 'push'
        run: uv publish --trusted-publishing always