name: Rich-codex
on: [push]
jobs:
  rich_codex:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Project Environment
        uses: ./.github/actions/setup-project

      - name: Generate terminal images with rich-codex (no log file)
        env:
          FORCE_COLOR: 1
          TERMINAL_WIDTH: 85
        run: |
          uv run rich-codex \
            --skip-git-checks \
            --no-confirm \
            --clean-img-paths docs/img/*.svg

      - name: Commit changed rich-codex images
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "docs: update rich-codex images"
