name: Rich-codex
on: [push]
jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Project Environment
        uses: ./.github/actions/setup-project

      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@v1
        env:
          LOG_SAVE: "false"
        with:
          commit_changes: "true"
          clean_img_paths: docs/img/*.svg
