name: Build arm64 Docker image

on:
  push:
    branches:
      - pr-21

permissions:
  contents: read
  packages: write

env:
  IMAGE_BASE: ghcr.io/singular-genomics/g4x-helpers

jobs:
  build-arm64:
    name: Build arm64 image
    if: github.repository == 'singular-genomics/g4x-helpers'
    runs-on: ubuntu-24.04-arm
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build & push arm64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          platforms: linux/arm64
          tags: |
            ${{ env.IMAGE_BASE }}:latest-arm64
            ${{ env.IMAGE_BASE }}:${{ github.ref_name }}-arm64
          cache-from: type=registry,ref=${{ env.IMAGE_BASE }}:cache-arm64
          cache-to: type=registry,ref=${{ env.IMAGE_BASE }}:cache-arm64,mode=max