name: Build Docker image on new tag

on:
  push:
    branches:
      - pr-21

permissions:
  contents: read
  packages: write

env:
  IMAGE_BASE: ghcr.io/singular-genomics/g4x-helpers

jobs:
  build-amd64:
    name: Build amd64 image
    if: github.repository == 'singular-genomics/g4x-helpers'
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build & push amd64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_BASE }}:latest-amd64
            ${{ env.IMAGE_BASE }}:${{ github.ref_name }}-amd64
          # Optional per-arch cache (you can adjust names):
          cache-from: type=registry,ref=${{ env.IMAGE_BASE }}:cache-amd64
          cache-to: type=registry,ref=${{ env.IMAGE_BASE }}:cache-amd64,mode=max

  build-arm64:
    name: Build arm64 image
    if: github.repository == 'singular-genomics/g4x-helpers'
    runs-on: ubuntu-24.04-arm
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU (needed for cross emulation if any tooling expects amd64, optional here)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build & push arm64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            ${{ env.IMAGE_BASE }}:latest-arm64
            ${{ env.IMAGE_BASE }}:${{ github.ref_name }}-arm64
          cache-from: type=registry,ref=${{ env.IMAGE_BASE }}:cache-arm64
          cache-to: type=registry,ref=${{ env.IMAGE_BASE }}:cache-arm64,mode=max

  create-manifest:
    name: Create multi-arch manifest
    if: github.repository == 'singular-genomics/g4x-helpers'
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Create and push manifest for latest
        run: |
          docker buildx imagetools create \
            --tag $IMAGE_BASE:latest \
            $IMAGE_BASE:latest-amd64 \
            $IMAGE_BASE:latest-arm64

      - name: Create and push manifest for versioned tag
        run: |
          docker buildx imagetools create \
            --tag $IMAGE_BASE:${{ github.ref_name }} \
            $IMAGE_BASE:${{ github.ref_name }}-amd64 \
            $IMAGE_BASE:${{ github.ref_name }}-arm64